### ISSUE TITLE
 What task can you perform?

### ISSUE THREAD

**Issue by marciojunior88** [bancodobrasil/stop-analyzing-api#10]
I would like to have a task to perform

**Comment by tiagostutz** [comment]
Hi @marciojunior88 ! We're so glad to have you on board.!
I'm taking a look here at the opened issues and the project backlog and will create an issue for you.

Do you already have some experience with Go or are you starting it like the most of us? What other technologies you like to work with?

**Comment by tiagostutz** [comment]
Hi @marciojunior88 !
Sorry for the huge delay on that. 🥺 
I didn't have a backlog yet so I couldn't just pick and issue and assign to you, I was designing it. 

The good news is that it is ready to go! If you want to grab, go to https://github.com/bancodobrasil/stop-analyzing-api/issues/16 and give a comment so I can assign it to you! It will be really nice to have your contribution here.

Thanks for your patience and hope you could take that. ⭐
