### ISSUE TITLE
Follow a Go project pattern/guidelines

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-api#11]
Hi there! 
Anyone has any suggestion on a project structure, best practies, linting, pattern, etc for us to follow?

As we are in the beginning of the project, I think that's a good opportunity for us to choose one and make the refactor. 

Suggestions?

**Comment by vinnicius** [comment]
Looking for project structure standards in go, i find that there's no specific package structure att all (: 

But we can use some good practices and patterns from popular projects. I found guidelines here (https://github.com/golang-standards/project-layout) that are useful when we have multiple packages in the same repo. Think that this is a good start.

**Comment by tiagostutz** [comment]
Nice, @vinnicius ! I agree with you.

Do you want to make this reactor and submit a PR? It would be really nice to have the project follow those guidelines.

**Comment by vinnicius** [comment]
Sure! I’m gonna take that.

**Comment by tiagostutz** [comment]
Sweet.! 
Go ahead. We well be waiting for the PR. ☀️

**Comment by GreenStage** [comment]
Here are my two cents on this:

 IMO , more important than following any dogmatic layout, is separating concerns and naming packages in a way that transparently describes their implementation uniqueness. 

For instance, I would avoid naming a package "db". E.g. while you may have only integration with a postgres database today, you might want to have a Mongo database tomorrow.  Your application could even need to switch between the two at runtime.  

Sorting the Mongo db client into a "mongo" package and the postgres one into a "postgres" package would allow easy polymorphism from higher layers. This ties up with my next recommendation:


 **Declare interfaces on the packages that need them, not in packages that implement them**: This can easily work as the package "contract", by exposing all interfaces it needs to work, without caring how they are implemented. Following the database example, you could have a package "http-handlers" that declares the interface "GetUser", which both the postgres and the mongo package implement.

Here is a recent article about it that explains it better than I could ever do:
https://www.reddit.com/r/golang/comments/hha3pa/why_you_should_write_interfaces_perpackage/

**Comment by vinnicius** [comment]
From the reddit article, I ended up here https://github.com/Evertras/go-interface-examples/tree/master/local-interfaces

It's not quite straightforward or simple to understand, but it's a great starting guideline. What you all think about it?

**Comment by tiagostutz** [comment]
Go for it, @vinnicius !

Thanks a lot @GreenStage.! 🚀

**Comment by eniovalo** [comment]
@vinnicius , thanks for the guidelines link, its project structure seems nice. =]

@GreenStage , thanks for the link about interfaces locally, it sounds good. :)

I don't know much about Golang, but we could configure a script to run `go fmt` and `golint` to format and to validate the code before each commit. :slightly_smiling_face:

**Comment by tiagostutz** [comment]
> @vinnicius , thanks for the guidelines link, its project structure seems nice. =]
> 
> @GreenStage , thanks for the link about interfaces locally, it sounds good. :)
> 
> I don't know much about Golang, but we could configure a script to run `go fmt` and `golint` to format and to validate the code before each commit. 🙂

What do you think @vinnicius ? Could we put this in the scope of this issue or do you think we should open another issue for that?

**Comment by vinnicius** [comment]
> > @vinnicius , thanks for the guidelines link, its project structure seems nice. =]
> > @GreenStage , thanks for the link about interfaces locally, it sounds good. :)
> > I don't know much about Golang, but we could configure a script to run `go fmt` and `golint` to format and to validate the code before each commit. 🙂
> 
> What do you think @vinnicius ? Could we put this in the scope of this issue or do you think we should open another issue for that?

Since this could become a standard pattern for our projects, and for tracking purposes, I think that another issue is more suitable in this case!

**Comment by tiagostutz** [comment]
Hi @vinnicius ! 
Are you still working on this issue? I'm asking because if you are out of time now, we could ask @GreenStage  whether he wants to take this issue as we've just merged his #15 PR. Of course we can create another issue for you when you prefer to. 
But if you are working on that, never mind, we are gladly waiting for your PR.! 🏁

**Comment by vinnicius** [comment]
Oh, i was working on this, using @GreenStage guidelines that i found to be very interesting! But also having a hard time understanding how to make ir work. If he wants to take this one that will be great! And i'll take another issue in the meantime

**Comment by GreenStage** [comment]
Hallo @tiagostutz , can you clarify some questions for me?

1.  The whole cmd/service boot logic seems a big overkill, if you ask me. This being an HTTP server , the only commands are start/stop. We don't need a cli for this. The server could start when the applications starts and exit when it stops (ctrl+c). This would also remove a lot of code. What do you think?

2.  prisma generates the models on the same file as the db client functions. this makes it impossible to have abstraction between the router and the db implementation since the router needs to be aware of the models as well.  If the project grows complex, this will be a pain in the head, because you wont be able to mock the database layer when testing the router functions :/ 

Not sure what you want to do regarding this last point, I would suggest either remove the database.go (having the router calling the prisma client directly), or considering alternatives to prisma.

**Comment by tiagostutz** [comment]
Hi there @GreenStage, good points you bring.!

>     1. The whole cmd/service boot logic seems a big overkill, if you ask me. This being an HTTP server , the only commands are start/stop. We don't need a cli for this. The server could start when the applications starts and exit when it stops (ctrl+c). This would also remove a lot of code. What do you think?

We can improve this, but the point is that beyond the HTTP server start/stop this program will have some migration commands also to bring data and, although that could be in a separated project, this would be an overkill also because we would have to separate all the model stuff and business logic in a separate lib to be used in both projects (http server and migration cli) and this migration cli would have just this simple function. 
That being said, I agree with you that we could follow a more simple approach of just checking the flags and deciding to start the in a "server mode" or "migration mode". If you would like to make this enhancement, feel free to open an issue and the PR. All improvements are welcome, for sure. 👍🏻 



>     2. prisma generates the models on the same file as the db client functions. this makes it impossible to have abstraction between the router and the db implementation since the router needs to be aware of the models as well.  If the project grows complex, this will be a pain in the head, because you wont be able to mock the database layer when testing the router functions :/

Ok, I see. I think we have wrongly named the file `database.go` because it is not - as you said - an actually database abstraction layer. The DB abstraction layer is done by Prisma itself. So, this `database.go` is more like a service (god old Business Domain) functions file and, being that, it should be separated by domain. Checking the code, you see that those functions are just orchestrating prisma calls sequences and doing some business logic (simple because the problem here is simple).
So I think we could make a refactor this after merging #14 changing the package name and splitting the functions in two files: Item related service functions and Tag related services functions. Then, the router controller would have something like:
```
//Controller .
type Controller struct {
	itemService *service.ItemService
	tagService *service.TagService
}
```

instead of the current

```
//Controller .
type Controller struct {
	database *db.DatabasePrisma
}
```

I don't know if there's a better name then "service", I'm open to new naming conventions.

About moving away from Prisma, we can decide that later if we have problems with it. But I'd like to hear what would be your choice if we decide to replace Prisma.

What do you think?
