### ISSUE TITLE
I would like to contribute

### ISSUE THREAD

**Issue by rafamarts** [bancodobrasil/stop-analyzing-api#12]
Hello guys,

I have basic experience in Golang, and would like to improve it. Could I help the project with some issue?

Thank you!

**Comment by tiagostutz** [comment]
Hi @rafamarts ! Sorry for the late response... !

I'm going to create an issue for you and will come back here with it.

That's so nice to also have you here. It will be of great value for the project to have contributors working on both frontend and backend.

**Comment by tiagostutz** [comment]
Hi there @rafamarts !! 

Do you want to take the issue #19 ? If so, please comment in the issue and I'll assign it to you. 

Sorry for the late response... 🤒

**Comment by rafamarts** [comment]
Great!! Let's do it!! I can get the issue #19.

**Comment by tiagostutz** [comment]
Great!! Just comment there on the issue, please, so I can assign it to you.

Welcome on board! 😃
