### ISSUE TITLE
Run go test before each commit or show a console log to run go test before push

### ISSUE THREAD

**Issue by eniovalo** [bancodobrasil/stop-analyzing-api#19]
Hi,

We could configure to run `go test` on all project before each commit to validate if the changings break anything. Or if tests are too slow, we could display a console log after commit to remember to run `go test` before push. =]

What do you think?

**Comment by zamariola** [comment]
It's a good point. We can configure the travis-ci and the goreportcard. btw, ours is A+
https://goreportcard.com/report/github.com/bancodobrasil/stop-analyzing-api

**Comment by tiagostutz** [comment]
Nice.!

Could we offer this issue to Rafamarts, at #12? Including the `go test` feature and the travis-ci thing.

What do you think?

**Comment by eniovalo** [comment]
@tiagostutz ,
I think It's ok. 🙂

**Comment by eniovalo** [comment]
> It's a good point. We can configure the travis-ci and the goreportcard. btw, ours is A+
> https://goreportcard.com/report/github.com/bancodobrasil/stop-analyzing-api

@zamariola ,
I didn't know this site, it is really nice to see the reports.
Thanks. 🙂

**Comment by rafamarts** [comment]
Hi guys,

Please, assign to me. I can work on that..

Thank you!

**Comment by tiagostutz** [comment]
Nice!
Assigned to you, @rafamarts!! Go for it.!

**Comment by paulo-vieira-centeno** [comment]
I'd like to help with this issue.
Can you assign it to me?

**Comment by tiagostutz** [comment]
Done! Go for it @paulo-vieira-centeno !!

@rafamarts I assigned to @paulo-vieira-centeno and we will work on another issue soon, ok? Thanks!!

**Comment by paulo-vieira-centeno** [comment]
@tiagostutz , I was thinking in writing a bash script that performs some of the steps described in README.md file, except for the steps related to the build of the API. These steps would be done in the host machine, so it would make it easier to start developing/testing the API locally. We could also setup the githooks as one of these steps. What do you think about?

**Comment by tiagostutz** [comment]
Hi @paulo-vieira-centeno !

Sounds good to me! Please, go ahead. 🚀

**Comment by paulo-vieira-centeno** [comment]
@tiagostutz , I've already done my local changes in a local branch. I tryed to push that repo to github, but got a '403 forbidden'.  Can you give me the appropriate permissions to be able to push my branch to the repository?

**Comment by eniovalo** [comment]
Hi @paulo-vieira-centeno ,
I think you need to fork the project and after send a Pull Request. =]
Like in this [article](https://github.com/firstcontributions/first-contributions#fork-this-repository) and [here](https://github.com/bancodobrasil/stop-analyzing-api/blob/master/CONTRIBUTING.md) there is more information.

**Comment by paulo-vieira-centeno** [comment]
Thanks for the instructions, @eniovalo

**Comment by eniovalo** [comment]
@paulo-vieira-centeno , you're welcome. 🙂
