### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by douglasferlini** [bancodobrasil/stop-analyzing-api#2]
Hello,

I have about 15 years of experience with software development but only a few coding in GO.
I think that I can contribute in any task that is needed.

Regards,
Douglas

**Comment by tiagostutz** [comment]
Hi @douglasferlini ! Sorry for the delayed answear... for some reason the notification of this project weren't arriving... 🤕 

That's awesome to have you here. Let's get this party started. I'm going to create an issue for you right away and will come back here to bring you the link.

**Comment by tiagostutz** [comment]
@douglasferlini first of all, I'm so so sorry for the late response... 😧  
I was on a rush with the [stop-analyzing-embed](https://github.com/bancodobrasil/stop-analyzing-embed) and couldn't open an issue with a good timing here.

But finally, I just created this issue #5 for you.! If you like to grap this, just post comment there and I'll assign it to you right now!
