### ISSUE TITLE
Developer wanting to get involved in the OSS community

### ISSUE THREAD

**Issue by paulo-vieira-centeno** [bancodobrasil/stop-analyzing-api#23]
Hello
I am a Developer with solid background in the Telecom industry, specializing in C ++. I am interested in starting to collaborate on Open Source projects in order to improve my Go development skills. I found your project to be a good gateway for this community. I would like more information on how to collaborate.

**Comment by tiagostutz** [comment]
Hello and welcome to Stop Analyzing, @paulo-vieira-centeno .! 👋🏻

First of all thanks for offering help to this project. I’m sure we are building a simple yet really interesting and useful tool here. 

If you are looking for a place to practice go and improve your OSS skills, you reached the right place.! We are all learning together here.

I’ll create an issue for you asap, but meanwhile, would you like to take a look at #19? It is a bit stale so if you want to start with that, comment on the issue and I’ll assign that to you right away. 

Nice to have you on board! 🥂

**Comment by paulo-vieira-centeno** [comment]
Thanks, I'll take a look at #19 
Nice to meey you guys too!
