### ISSUE TITLE
docker-compose command failing

### ISSUE THREAD

**Issue by KarineValenca** [bancodobrasil/stop-analyzing-api#31]
Hello! I'm facing this issue while running `docker-compose build` command:

<img width="565" alt="Screen Shot 2021-01-08 at 07 45 07" src="https://user-images.githubusercontent.com/8433187/104007073-1e415e00-5186-11eb-9f54-59981a4021e4.png">

```
Step 7/13 : RUN go run github.com/prisma/prisma-client-go generate --schema=/app/scripts/prisma/schema.prisma
 ---> Running in 6ea99da5dd8b
# github.com/prisma/prisma-client-go
/go/pkg/mod/github.com/prisma/prisma-client-go@v0.2.0/generator.go:43:6: undefined: errors.Is
note: module requires Go 1.13
```

Probably, the Go version from the Dockerfile is not compatible with the Prisma version.

**Comment by tiagostutz** [comment]
Hi @KarineValenca!
I'll take a look at this.

**Comment by tiagostutz** [comment]
Fixed this. =)
