### ISSUE TITLE
I can contribute with Go :)

### ISSUE THREAD

**Issue by zamariola** [bancodobrasil/stop-analyzing-api#4]
Hello Guys!
First of all, awesome idea encouraging the open-source community.
I can help with golang and APIs. Just let me know if you guys foresee anything.
Thanks!

**Comment by tiagostutz** [comment]
Hi there 👋  @zamariola !!
Nice to have you on board.! 🚢 

Thanks for your kind words. We are learning how to do all this stuff, but it's been a great adventure. Welcome to that trip.

As you can help, I'm going to open an issue for you and will link it here when its done for you to take a look and grab that. 
Ok?

**Comment by tiagostutz** [comment]
Hi @zamariola !

I just created this issue #6 for you. If you are interested in taking that, please post a comment there and let's do this! 🚴

**Comment by zamariola** [comment]
Cool! I can grab that. I'm going to ask a few questions there, just to get more info.

**Comment by zamariola** [comment]
Closing to work on #8
