### ISSUE TITLE
Implement migration and database creation startup flags

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-api#6]
Implement a command line flag `--with-migration <url>` that will instruct the main program to download data from a URL and insert in the database before bringing the server up.

If the database already has data, throw an error. We could create another flag `--recreate-database` that will drop and create a database from scratch. So, if the user executes:
```
$ stop-analyzing-api --recreate-database --with-migration https://endpoint-with-migration-data
```

The service will perform a clean start loading this data. This will be very useful for development porpuses.

How about that?

@jairsjunior or @flaviostutz, any thoughts?

**Comment by zamariola** [comment]
Hello guys! 
Quick question here... Do we have any thoughts about content, protocol or anything that the Url (endpoint-with-migration-data) is going to provide? 
Are we going to expose this URL with the migration information inside the "stop-analyzing-api" service itself, so we would use it to migrate from an existing scenario to another OR are we going to have a third party service with the content to be migrated?

Thanks!

**Comment by tiagostutz** [comment]
Hi @zamariola ! Good point!

We will have a mix of the second and third option. We are going to have the data coming from third parties and those third parties will follow the spec that will be defined in #7 . This way we will be able to decouple "data gathering" from "data presenting" in a smooth manner. 

So, I think we can discuss in #7 this content spec and protocol. Agreed?

**Comment by tiagostutz** [comment]
Hi @zamariola !

I think you would be interested in taking a look or maybe giving some thoughts at #8 .
