### ISSUE TITLE
Implement the migrationFromFile service

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-api#7]
The service will receive a JSON filePath, validate if the schema is ok and insert the data from this file in the local database.

Just as a starting point, I created the package `migration` with the function `migrateFromURL` and `migrateFromFile`. The ideia is that when this issue is ready, the `migrateFromURL` with be as easy as downloading the file and invoking this function. But that's **not** on the scope here. We will tie all of this when the #6 is ready too.

How about this?

**Comment by eniovalo** [comment]
Hi @tiagostutz,
Could I try to do this issue? =]

**Comment by tiagostutz** [comment]
Its yours.! 

Go ahead! =)

**Comment by tiagostutz** [comment]
Hey, @eniovalo just for you to know, I just updated some commiting guidelines here https://github.com/bancodobrasil/stop-analyzing-api/blob/master/CONTRIBUTING.md#commiting-and-pr-guidelines

I think it would be good for you to notice that and if you have any suggestion, please feel free to open an issue with that.

**Comment by eniovalo** [comment]
Thanks @tiagostutz =]

**Comment by eniovalo** [comment]
Hi @tiagostutz ,
The schema to validate the Json file is the same as the issue #8 ?
```json
[{
    "title": "string",
    "subtitle": "string",
    "contentURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
}]
```

**Comment by tiagostutz** [comment]
Yep, that's the schema to be validated against @eniovalo !

**Comment by eniovalo** [comment]
@tiagostutz , Thanks. =]

**Comment by eniovalo** [comment]
Hi @tiagostutz ,
Like issue #6 , if the database has already data, I need to throw an error? And I need to create an option to recreate the database from JSon file?

Thanks.

**Comment by tiagostutz** [comment]
Hi @eniovalo  ! Sorry for the late response... this week was a mess, but everything is fine now.! =)

I think it could throw an error and you could have an option passed as a `boolean` param named `resetDatabase` that will always recreate the database before running the migration. Sounds good?

**Comment by eniovalo** [comment]
@tiagostutz , no problem. 😉
Sounds good, thanks. =]
