### ISSUE TITLE
Implement an example of the "contract" between backend and frontend

### ISSUE THREAD

**Issue by tiagostutz** [bancodobrasil/stop-analyzing-api#8]
We could implement a mock server that delivers a Mock data just to have the "spec by example". 

What do you think? We could design here the request/response protocol and then somenone grabs this issue to implement the mock server..

**Comment by eniovalo** [comment]
@tiagostutz I think it is a great ideia. So frontend could test the integration with backend. =]

**Comment by tiagostutz** [comment]
Correct!
And, as the design is to have a data server, the interface with the mock data server or with a actually data server will be the same. 😃

**Comment by jairsjunior** [comment]
To start this conversation, we need to list the basic information that will be transit between the embed and api projects.
I will start with some properties and objects

**Image** Object
- name
- filePath
- []Tag

**Tag** Object
- name
- []Images

**Comment by tiagostutz** [comment]
Nice! Good start. I see that you started the spec in the Go side here, right. I was thinking about the REST API that this component will invoke to get the data it will use to store and expose to the frontend.

I was thinking about not stricting only to images, building a more generic API as this could be used for videos, for instance. Agree?

I'll write some documentation as spec here for you all to review and give your opinions.  (Documentation Drive Development 😆)

## Using th API

To get the choice options to be used on your **stop-analyzing-api** service, you could use this API that has the following endpoints:

### Get all options

Retrieve all items and can be filtered using query params on the URL by: 
- `title`: item title text (e.g.: _Blush Tulle and Lace Wedding Dress_)
- `tags`: comma separated list of tags (e.g.: _dress,long,vintage,tulle_)
- `subtitle`: item subtitle text (e.g.: _blush tulle and lace wedding dress with vintage ballerina pink ribbon details and gathered detachable sleeves for a romantic fairytale bride_)

**GET /items**

`$ curl http://localhost:8008/items`
`$ curl http://localhost:8008/items?tags=blush,tulle`

**Return:**

```json
[{
    "title": "string",
    "subtitle": "string",
    "imageURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
},
{
    "title": "string",
    "subtitle": "string",
    "imageURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
}]

```

So I would change the **Image** object name for for **ChoiceOption** name. In REST API I'd keep the even more generic term "item" as this item will be a option only when the go exposes this data to stop analyzing...

What are your thougths?

**Comment by jairsjunior** [comment]
maybe change the imageURL to contentURL be an option? And what more information the frontend will need?

**Comment by tiagostutz** [comment]
Yep! You are right... correcting:


# Wedding dress Stop Analyzing Database

## Using th API

To get the choice options to be used on your **stop-analyzing-api** service, you could use this API that has the following endpoints:

### Get all options

Retrieve all items and can be filtered using query params on the URL by: 
- `title`: item title text (e.g.: _Blush Tulle and Lace Wedding Dress_)
- `tags`: comma separated list of tags (e.g.: _dress,long,vintage,tulle_)
- `subtitle`: item subtitle text (e.g.: _blush tulle and lace wedding dress with vintage ballerina pink ribbon details and gathered detachable sleeves for a romantic fairytale bride_)

**GET /items**

**Examples:**
```
$ curl http://localhost:8008/items
$ curl http://localhost:8008/items?tags=blush,tulle
```

**Return:**

```json
[{
    "title": "string",
    "subtitle": "string",
    "contentURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
},
{
    "title": "string",
    "subtitle": "string",
    "contentURL": "string",
    "tags": ["tag1", "tag2", "tag3"]
}]

```

How about that? I think we have a good starting point here.

**Comment by zamariola** [comment]
Cool! The json schema helped a lot. I'm getting a more well-defined picture of what we are trying to migrate and how to model it using structs.
This issue is absolutely related to te #6 one.

I think we may have two entry-points to call the same flow

**File Migration**:  Read file ---------------------------> parse struct -> process
**URL Migration**: Call http GET -> parse response -> ^

What do you guys think?
If so, I think I can create the http get call and parse a mocked response.

@eniovalo have you created any structs to hold the parsed file content?

Thanks!

**Comment by eniovalo** [comment]
> Cool! The json schema helped a lot. I'm getting a more well-defined picture of what we are trying to migrate and how to model it using structs.
> This issue is absolutely related to te #6 one.
> 
> I think we may have two entry-points to call the same flow
> 
> **File Migration**: Read file ---------------------------> parse struct -> process
> **URL Migration**: Call http GET -> parse response -> ^
> 
> What do you guys think?
> If so, I think I can create the http get call and parse a mocked response.
> 
> @eniovalo have you created any structs to hold the parsed file content?
> 
> Thanks!

Hi, @zamariola .
Sorry, I haven't created any structs yet. =(
I'm still studying the basics of Golang and analyzing how to solve issue #7 ...

**Comment by zamariola** [comment]
> > Cool! The json schema helped a lot. I'm getting a more well-defined picture of what we are trying to migrate and how to model it using structs.
> > This issue is absolutely related to te #6 one.
> > I think we may have two entry-points to call the same flow
> > **File Migration**: Read file ---------------------------> parse struct -> process
> > **URL Migration**: Call http GET -> parse response -> ^
> > What do you guys think?
> > If so, I think I can create the http get call and parse a mocked response.
> > @eniovalo have you created any structs to hold the parsed file content?
> > Thanks!
> 
> Hi, @zamariola .
> Sorry, I haven't created any structs yet. =(
> I'm still studying the basics of Golang and analyzing how to solve issue #7 ...

Don't you worry! I'm going to create a draft and share it with you!

**Comment by tiagostutz** [comment]
Great, @zamariola !

> I think we may have two entry-points to call the same flow
> File Migration: Read file ---------------------------> parse struct -> process
> URL Migration: Call http GET -> parse response -> ^

Let's implement the way you suggested. When you commit the structs on your fork, please put a `ref #8` on the commit message so this commit will appear here in the issue and we can take a look at the progress. 😃

**Comment by eniovalo** [comment]
> 
> Don't you worry! I'm going to create a draft and share it with you!

@zamariola , Thanks. 🙂

**Comment by zamariola** [comment]
@tiagostutz @eniovalo 
I don't know if we already have a final word about it:  
are we going to store the options using the ChoiceBoardModel, so we're going to have title and subtitle there or are we going to use another model?

My next step on #6 is the actual item creation.

Thanks!!

**Comment by tiagostutz** [comment]
Hi @zamariola! We don't have a final word yet, but let's make the decision right now:
Following what we are implementing in https://github.com/bancodobrasil/stop-analyzing-embed/issues/34, the endpoint of to retrieve the next choice will return:

```json
{
  "completeness": 0.3,
  "choices": [
    {
      "title": "stringt1",
      "subtitle": "strings1",
      "contentURL": "stringc1",
      "tags": ["tag11", "tag12", "tag13"]
    },
    {
      "id": "5bdae89eeae8a99",
      "title": "stringt2",
      "subtitle": "strings2",
      "contentURL": "stringc2",
      "tags": ["tag21", "tag12", "tag13"]
    },
    {
      "id": "5bdae890aa0a0993e",
      "title": "stringt3",
      "subtitle": "strings3",
      "contentURL": "stringc3",
      "tags": ["tag21", "tag12", "tag31"]
    }
  ]
}
```

Those choices are `Items` (in our model). So that's the current proposal. Do you agree with it or have some suggestions to share? We are wide open to that...

**Comment by zamariola** [comment]
Perfect! I'm going to add it.

**Comment by tiagostutz** [comment]
Just to update things a little, we are moving from a "tag" approach to an "attribute" approach. So the JSON returned to the frontend will be:
```
{
  "completeness": 0.3,
  "choices": [
    {
      "id": "5bdae89eadfea93",
      "title": "string-ttitle-1",
      "subtitle": "string-sub-1",
      "contentURL": "string-content-1",
      "attributes": [{
            "attr-name-1":"attr-value-1",
            "attr-name-2":"attr-value-2"
       }]
    },
    {
      "id": "5bdae89eeae8a99",
      "title": "string-ttitle-2",
      "subtitle": "string-sub-2",
      "contentURL": "string-content-2",
      "attributes": [{
            "attr-name-31":"attr-value-31",
            "attr-name-23":"attr-value-23"
       }]
  }]
}
```
