### ISSUE TITLE
I want to contribute to this project 

### ISSUE THREAD

**Issue by GreenStage** [bancodobrasil/stop-analyzing-api#9]
Cheers,
I have experience in go,

Was looking for smth to contribute to in my spare time,

If there is anything you are willing to let me take, would be lovely

Thanks :D

**Comment by tiagostutz** [comment]
Cheers, @GreenStage !

Absolutely. I'm going to open an issue for you and will come back here to link it asap so we can get started. 🚀 

We are so glad to have one more Gopher here...! ⚡

**Comment by tiagostutz** [comment]
Hi @GreenStage !
Sorry for the late reply. Do you have any experience with building crawlers?

**Comment by GreenStage** [comment]
@tiagostutz  cheers,

No i have not

**Comment by tiagostutz** [comment]
Ok! 
I'm organizing here the issues and will create one for you. Meanwhile, do you think you could contribute sharing some thoughts in #11 as you have some experience in Golang projects? It would be nice to have your opinio on this.!

**Comment by tiagostutz** [comment]
Hi there @GreenStage !
Would you like to contribute taking the issue #15 ?

**Comment by GreenStage** [comment]
Cheers, glad to help with what i can.
You can assign me to this issue aswell

**Comment by tiagostutz** [comment]
Perfect.!

Just assigned the issue #11 to you.
